language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly
  - hhvm

install:
  - composer update --no-interaction --prefer-stable $PREFER_LOWEST

script:
  - vendor/bin/phpunit --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
